// features/subscriptions/config/plan-features.ts
// Source of truth for the comparison table — UI only

export const PLAN_COMPARISON = {
  categories: [
    {
      label: "Stores & Team",
      features: [
        {
          key: "maxStores",
          label: "Stores",
          Free: "1",
          Starter: "1",
          Growth: "3",
          Pro: "Unlimited",
        },
        {
          key: "maxTeamMembers",
          label: "Team members",
          Free: "2",
          Starter: "5",
          Growth: "10",
          Pro: "Unlimited",
        },
        {
          key: "multiLocation",
          label: "Multi-location",
          Free: false,
          Starter: false,
          Growth: true,
          Pro: true,
        },
      ],
    },
    {
      label: "Orders & Inventory",
      features: [
        {
          key: "orders",
          label: "Orders management",
          Free: true,
          Starter: true,
          Growth: true,
          Pro: true,
        },
        {
          key: "inventory",
          label: "Inventory tracking",
          Free: true,
          Starter: true,
          Growth: true,
          Pro: true,
        },
        {
          key: "bulkActions",
          label: "Bulk actions",
          Free: false,
          Starter: false,
          Growth: true,
          Pro: true,
        },
        {
          key: "quotes",
          label: "Quote requests",
          Free: false,
          Starter: true,
          Growth: true,
          Pro: true,
        },
        {
          key: "customOrders",
          label: "Custom orders",
          Free: false,
          Starter: true,
          Growth: true,
          Pro: true,
        },
      ],
    },
    {
      label: "Customers",
      features: [
        {
          key: "customers",
          label: "Customer management",
          Free: true,
          Starter: true,
          Growth: true,
          Pro: true,
        },
        {
          key: "customerGroups",
          label: "Customer groups",
          Free: false,
          Starter: false,
          Growth: true,
          Pro: true,
        },
      ],
    },
    {
      label: "Payments & Billing",
      features: [
        {
          key: "paystackGateway",
          label: "Paystack gateway",
          Free: true,
          Starter: true,
          Growth: true,
          Pro: true,
        },
        {
          key: "bankTransfer",
          label: "Bank transfer",
          Free: true,
          Starter: true,
          Growth: true,
          Pro: true,
        },
        {
          key: "invoicing",
          label: "Invoicing",
          Free: true,
          Starter: true,
          Growth: true,
          Pro: true,
        },
        {
          key: "taxSettings",
          label: "Tax settings",
          Free: false,
          Starter: true,
          Growth: true,
          Pro: true,
        },
      ],
    },
    {
      label: "Shipping",
      features: [
        {
          key: "shippingZones",
          label: "Shipping zones",
          Free: false,
          Starter: true,
          Growth: true,
          Pro: true,
        },
        {
          key: "shippingIntegrations",
          label: "Fez & Shipbubble",
          Free: false,
          Starter: false,
          Growth: true,
          Pro: true,
        },
      ],
    },
    {
      label: "Marketing & Campaigns",
      features: [
        {
          key: "emailCampaigns",
          label: "Email campaigns",
          Free: false,
          Starter: true,
          Growth: true,
          Pro: true,
        },
        {
          key: "sms",
          label: "SMS campaigns",
          Free: false,
          Starter: false,
          Growth: true,
          Pro: true,
        },
        {
          key: "monthlyCredits",
          label: "Monthly credits",
          Free: "0",
          Starter: "500",
          Growth: "2,000",
          Pro: "5,000",
        },
        {
          key: "subscriberManagement",
          label: "Subscriber management",
          Free: false,
          Starter: true,
          Growth: true,
          Pro: true,
        },
      ],
    },
    {
      label: "Analytics & Reports",
      features: [
        {
          key: "analytics",
          label: "Analytics dashboard",
          Free: false,
          Starter: false,
          Growth: true,
          Pro: true,
        },
        {
          key: "analyticsRetention",
          label: "Data retention",
          Free: "—",
          Starter: "—",
          Growth: "90 days",
          Pro: "365 days",
        },
        {
          key: "revenueReports",
          label: "Revenue reports",
          Free: false,
          Starter: false,
          Growth: true,
          Pro: true,
        },
        {
          key: "staffActivityLogs",
          label: "Staff activity logs",
          Free: false,
          Starter: false,
          Growth: true,
          Pro: true,
        },
      ],
    },
    {
      label: "Storefront",
      features: [
        {
          key: "storefront",
          label: "Online storefront",
          Free: true,
          Starter: true,
          Growth: true,
          Pro: true,
        },
        {
          key: "customDomain",
          label: "Custom domain",
          Free: false,
          Starter: false,
          Growth: false,
          Pro: true,
        },
        {
          key: "blogModule",
          label: "Blog",
          Free: false,
          Starter: true,
          Growth: true,
          Pro: true,
        },
        {
          key: "productReviews",
          label: "Product reviews",
          Free: false,
          Starter: false,
          Growth: true,
          Pro: true,
        },
      ],
    },
    {
      label: "Integrations",
      features: [
        {
          key: "googleAnalytics",
          label: "Google Analytics",
          Free: false,
          Starter: false,
          Growth: true,
          Pro: true,
        },
        {
          key: "facebookPixel",
          label: "Facebook Pixel",
          Free: false,
          Starter: false,
          Growth: true,
          Pro: true,
        },
        {
          key: "zohoIntegration",
          label: "Zoho CRM",
          Free: false,
          Starter: false,
          Growth: false,
          Pro: true,
        },
        {
          key: "apiAccess",
          label: "API access",
          Free: false,
          Starter: false,
          Growth: false,
          Pro: true,
        },
        {
          key: "webhooks",
          label: "Webhooks",
          Free: false,
          Starter: false,
          Growth: false,
          Pro: true,
        },
      ],
    },
    {
      label: "Support",
      features: [
        {
          key: "emailSupport",
          label: "Email support",
          Free: false,
          Starter: true,
          Growth: true,
          Pro: true,
        },
        {
          key: "prioritySupport",
          label: "Priority support",
          Free: false,
          Starter: false,
          Growth: false,
          Pro: true,
        },
        {
          key: "dedicatedSupport",
          label: "Dedicated account manager",
          Free: false,
          Starter: false,
          Growth: false,
          Pro: true,
        },
      ],
    },
  ],
} as const;

export const PLAN_NAMES = ["Free", "Starter", "Growth", "Pro"] as const;
export type PlanName = (typeof PLAN_NAMES)[number];
